=== copyy1/test/xml/circuito.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.uniovi.es"
	xmlns="http://www.uniovi.es"
	elementFormDefault="qualified">
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="longitudCircuito" />
				<xs:element ref="anchuraMedia" />
				<xs:element ref="fechaCarrera" />
				<xs:element ref="horaInicio" />
				<xs:element ref="numVueltas" />
				<xs:element ref="localidad" />
				<xs:element ref="pais" />
				<xs:element ref="referencias" />
				<xs:element ref="fotografias" />
				<xs:element ref="videos" />
				<xs:element ref="coordenadas" />
				<xs:element ref="tramos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="longitudCircuito">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="anchuraMedia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fechaCarrera" type="xs:date" />
	<xs:element name="horaInicio" type="xs:time" />
	<xs:element name="numVueltas" type="xs:int" />
	<xs:element name="localidad" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia" type="xs:string" />
	<xs:element name="fotografias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="fotografia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografia" type="xs:string" />
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video" type="xs:string" />
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud" >
		<xs:simpleType>
			<xs:restriction base="xs:float">
				<xs:minInclusive value="-180"></xs:minInclusive>
				<xs:maxInclusive value="180"></xs:maxInclusive>
			</xs:restriction>
		</xs:simpleType>	
	</xs:element>
	<xs:element name="latitud" >
		<xs:simpleType>
			<xs:restriction base="xs:float">
				<xs:minInclusive value="-90"></xs:minInclusive>
				<xs:maxInclusive value="90"></xs:maxInclusive>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="altitud" >
		<xs:simpleType>
			<xs:restriction base="xs:int">
				<xs:minInclusive value="0"></xs:minInclusive>
				<xs:maxInclusive value="16"></xs:maxInclusive>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="tramos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distanciaTramo" />
				<xs:element ref="coordenadas" />
				<xs:element ref="nSector" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="distanciaTramo">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:double">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="nSector" type="xs:int" />
</xs:schema>

=== copyy1/test/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuito xmlns="http://www.uniovi.es"
	xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.uniovi.es circuito.xsd">

    <nombre>Circuito Internacional de Losail</nombre>
    <longitudCircuito unidad="km">5.380</longitudCircuito>
    <anchuraMedia unidad="m">12</anchuraMedia>
    <fechaCarrera>2024-12-01</fechaCarrera>
    <horaInicio>18:00:00</horaInicio>
    <numVueltas>57</numVueltas>
    <localidad>Lusail</localidad>
    <pais>Qatar</pais>
    <referencias>
        <referencia>https://es.wikipedia.org/wiki/Circuito_Internacional_de_Losail</referencia>
        <referencia>https://www.lcsc.qa/</referencia>
        <referencia>https://www.formula1.com/en/racing/2024/qatar</referencia>
    </referencias>
    <fotografias>
        <fotografia>Lusail_Circuit.png</fotografia>
        <fotografia>Lusail_Recta.png</fotografia>
    </fotografias>
    <videos>
        <video>videoCircuito.mp4</video>
    </videos>
    <coordenadas>
        <longitud>51.449580</longitud>
        <latitud>25.489216</latitud>
        <altitud>13</altitud>
    </coordenadas>
    <tramos>
        <tramo>
            <distanciaTramo unidad="m">458.79</distanciaTramo>
            <coordenadas>
                <longitud>51.447504</longitud>
                <latitud>25.492913</latitud>
                <altitud>15</altitud>
            </coordenadas>
            <nSector>1</nSector>
        </tramo>
        <tramo>
            <distanciaTramo unidad="m">51.77</distanciaTramo>
            <coordenadas>
                <longitud>51.447798</longitud> 
                <latitud>25.493299</latitud>
                <altitud>15</altitud>
            </coordenadas>
            <nSector>1</nSector>
        </tramo>
        <tramo>
            <distanciaTramo unidad="m">47.05</distanciaTramo>
            <coordenadas>
                <longitud>51.448262</longitud>
                <latitud>25.493370</latitud>
                <altitud>15</altitud>
            </coordenadas>
            <nSector>1</nSector>
        </tramo>

        <tramo>
            <distanciaTramo unidad="m">198.15</distanciaTramo>
            <coordenadas>
                <longitud>51.449976</longitud>
                <latitud>25.492489</latitud>
                <altitud>14</altitud>
            </coordenadas>
            <nSector>1</nSector>
        </tramo>
        <tramo>
            <distanciaTramo unidad="m">49.38</distanciaTramo>
            <coordenadas>
                <longitud>51.450463</longitud>
                <latitud>25.492550</latitud>
                <altitud>14</altitud>
            </coordenadas>
            <nSector>1</nSector>
        </tramo>
        <tramo>
            <distanciaTramo unidad="m">48.81</distanciaTramo>
            <coordenadas>
                <longitud>51.450725</longitud>
                <latitud>25.492916</latitud>
                <altitud>14</altitud>
            </coordenadas>
            <nSector>1</nSector>
        </tramo>

        <tramo>
            <distanciaTramo unidad="m">160.55</distanciaTramo>
            <coordenadas>
                <longitud>51.450695</longitud>
                <latitud>25.494360</latitud>
                <altitud>13</altitud>
            </coordenadas>
            <nSector>1</nSector>
        </tramo>

        <tramo>
            <distanciaTramo unidad="m">386.08</distanciaTramo>
            <coordenadas>
                <longitud>51.453200</longitud>
                <latitud>25.496990</latitud>
                <altitud>14</altitud>
            </coordenadas>
            <nSector>1</nSector>
        </tramo>
        <tramo>
            <distanciaTramo unidad="m">104.42</distanciaTramo>
            <coordenadas>
                <longitud>51.453490</longitud>
                <latitud>25.497110</latitud>
                <altitud>14</altitud>
            </coordenadas>
            <nSector>1</nSector>
        </tramo>
        <tramo>
            <distanciaTramo unidad="m">30.39</distanciaTramo>
            <coordenadas>
                <longitud>51.453790</longitud>
                <latitud>25.497079</latitud>
                <altitud>14</altitud>
            </coordenadas>
            <nSector>1</nSector>
        </tramo>

        <tramo>
            <distanciaTramo unidad="m">116.23</distanciaTramo>
            <coordenadas>
                <longitud>51.454651</longitud>
                <latitud>25.496376</latitud>
                <altitud>14</altitud>
            </coordenadas>
            <nSector>1</nSector>
        </tramo>
        <tramo>
            <distanciaTramo unidad="m">30.56</distanciaTramo>
            <coordenadas>
                <longitud>51.454726</longitud>
                <latitud>25.496111</latitud>
                <altitud>14</altitud>
            </coordenadas>
            <nSector>1</nSector>
        </tramo>
        <tramo>
            <distanciaTramo unidad="m">27.92</distanciaTramo>
            <coordenadas>
                <longitud>51.454654</longitud>
                <latitud>25.495872</latitud>
                <altitud>14</altitud>
            </coordenadas>
            <nSector>1</nSector>
        </tramo>

        <tramo>
            <distanciaTramo unidad="m">139.47</distanciaTramo>
            <coordenadas>
                <longitud>51.453749</longitud>
                <latitud>25.494918</latitud>
                <altitud>14</altitud>
            </coordenadas>
            <nSector>1</nSector>
        </tramo>

        <tramo>
            <distanciaTramo unidad="m">92.90</distanciaTramo>
            <coordenadas>
                <longitud>51.453149</longitud>
                <latitud>25.494281</latitud>
                <altitud>15</altitud>
            </coordenadas>
            <nSector>2</nSector>
        </tramo>
        <tramo>
            <distanciaTramo unidad="m">32.72</distanciaTramo>
            <coordenadas>
                <longitud>51.453146</longitud>
                <latitud>25.493987</latitud>
                <altitud>15</altitud>
            </coordenadas>
            <nSector>2</nSector>
        </tramo>
        <tramo>
            <distanciaTramo unidad="m">41.46</distanciaTramo>
            <coordenadas>
                <longitud>51.453555</longitud>
                <latitud>25.493925</latitud>
                <altitud>15</altitud>
            </coordenadas>
            <nSector>2</nSector>
        </tramo>

        <tramo>
            <distanciaTramo unidad="m">305.04</distanciaTramo>
            <coordenadas>
                <longitud>51.456400</longitud>
                <latitud>25.494890</latitud>
                <altitud>15</altitud>
            </coordenadas>
            <nSector>2</nSector>
        </tramo>
        <tramo>
            <distanciaTramo unidad="m">62.89</distanciaTramo>
            <coordenadas>
                <longitud>51.456918</longitud>
                <latitud>25.494580</latitud>
                <altitud>15</altitud>
            </coordenadas>
            <nSector>2</nSector>
        </tramo>
        <tramo>
            <distanciaTramo unidad="m">63.15</distanciaTramo>
            <coordenadas>
                <longitud>51.456866</longitud>
                <latitud>25.494003</latitud>
                <altitud>15</altitud>
            </coordenadas>
            <nSector>2</nSector>
        </tramo>

        <tramo>
            <distanciaTramo unidad="m">124.26</distanciaTramo>
            <coordenadas>
                <longitud>51.456051</longitud>
                <latitud>25.493208</latitud>
                <altitud>14</altitud>
            </coordenadas>
            <nSector>2</nSector>
        </tramo>

        <tramo>
            <distanciaTramo unidad="m">97.79</distanciaTramo>
            <coordenadas>
                <longitud>51.455732</longitud>
                <latitud>25.492378</latitud>
                <altitud>13</altitud>
            </coordenadas>
            <nSector>2</nSector>
        </tramo>
        <tramo>
            <distanciaTramo unidad="m">34.50</distanciaTramo>
            <coordenadas>
                <longitud>51.455627</longitud>
                <latitud>25.492082</latitud>
                <altitud>13</altitud>
            </coordenadas>
            <nSector>2</nSector>
        </tramo>
        <tramo>
            <distanciaTramo unidad="m">39.20</distanciaTramo>
            <coordenadas>
                <longitud>51.455319</longitud>
                <latitud>25.491864</latitud>
                <altitud>13</altitud>
            </coordenadas>
            <nSector>2</nSector>
        </tramo>

        <tramo>
            <distanciaTramo unidad="m">158.44</distanciaTramo>
            <coordenadas>
                <longitud>51.453794</longitud>
                <latitud>25.491500</latitud>
                <altitud>13</altitud>
            </coordenadas>
            <nSector>2</nSector>
        </tramo>
        <tramo>
            <distanciaTramo unidad="m">43.89</distanciaTramo>
            <coordenadas>
                <longitud>51.453536</longitud>
                <latitud>25.491182</latitud>
                <altitud>13</altitud>
            </coordenadas>
            <nSector>2</nSector>
        </tramo>
        <tramo>
            <distanciaTramo unidad="m">33.58</distanciaTramo>
            <coordenadas>
                <longitud>51.453614</longitud>
                <latitud>25.490888</latitud>
                <altitud>13</altitud>
            </coordenadas>
            <nSector>2</nSector>
        </tramo>

        <tramo>
            <distanciaTramo unidad="m">194.44</distanciaTramo>
            <coordenadas>
